language: node_js
node_js:
  - "8"
install:
  - npm install -g codecov
  - npm install -g nyc
  - npm install -g tape
  - npm install -g tsc
  - npm install
script:
  - tsc
  - npm test
  - npm run report-coverage
